[pytest]
# 指定测试文件、类、方法的匹配规则
python_files = test_*.py
python_classes = Test*
python_functions = test_*

# 默认运行参数：
# -s: 允许打印 print 和 logging 信息到控制台
# -v: 详细输出
# --alluredir: 指定 Allure 原始数据的输出目录
# --clean-alluredir: 每次运行前自动清空旧的 Allure 数据
addopts = -s -v --alluredir=./allure-results --clean-alluredir